#!/usr/bin/env bun
/**
 * Harvests all custom version GUIDs from UE 5.7.3 source code and outputs
 * a TypeScript constant map.
 *
 * Pattern matched:
 *   const FGuid FXxx::GUID(0xAABBCCDD, 0xEEFF0011, 0x22334455, 0x66778899);
 *   F[Dev|Custom]VersionRegistration GRegister...(FXxx::GUID, ..., TEXT("FriendlyName"));
 */

import { readFileSync, readdirSync, statSync } from "fs";
import { join } from "path";

const UE_ROOT = join(import.meta.dir, "../../UnrealEngine-5.7.3-release/Engine");

function* walkCpp(dir: string): Generator<string> {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      yield* walkCpp(full);
    } else if (entry.endsWith(".cpp")) {
      yield full;
    }
  }
}

interface GuidEntry {
  structName: string;
  guid: string; // lowercase hex with hyphens
  friendlyName: string;
  file: string;
}

// Match: const FGuid FSomeName::GUID(0xABCD1234, 0xEFGH5678, 0xIJKL9012, 0xMNOP3456);
const GUID_RE =
  /const FGuid (\w+)::GUID\(\s*(0x[0-9A-Fa-f]+)\s*,\s*(0x[0-9A-Fa-f]+)\s*,\s*(0x[0-9A-Fa-f]+)\s*,\s*(0x[0-9A-Fa-f]+)\s*\)/;

// Match: FXxxRegistration GRegister...(FSomeName::GUID, ..., TEXT("Name"));
// Handles both TEXT("Name") and TEXT( "Name" ) forms, and multi-line / static_cast patterns.
// Strategy: just require VersionRegistration + TEXT("...") to appear in the nearby block.
const REG_RE = /F(?:Dev|Custom)VersionRegistration[\s\S]*?TEXT\(\s*"([^"]+)"\s*\)/;

function hexToU32(hex: string): number {
  return parseInt(hex, 16) >>> 0;
}

function formatGuid(a: string, b: string, c: string, d: string): string {
  const pad = (h: string, n: number) => hexToU32(h).toString(16).toUpperCase().padStart(n, "0");
  // UE FGuid format: AABBCCDD-EEFF0011-22334455-66778899
  return `${pad(a, 8)}-${pad(b, 8)}-${pad(c, 8)}-${pad(d, 8)}`;
}

const results: GuidEntry[] = [];
const seen = new Set<string>();

for (const file of walkCpp(UE_ROOT)) {
  const content = readFileSync(file, "utf8");
  const lines = content.split("\n");

  for (let i = 0; i < lines.length; i++) {
    const m = GUID_RE.exec(lines[i]);
    if (!m) continue;

    const structName = m[1];
    const guid = formatGuid(m[2], m[3], m[4], m[5]);
    if (seen.has(guid)) continue;

    // Look nearby (up to 8 lines after) for the registration, joining lines to handle multi-line
    let friendlyName = "";
    const nearby = lines.slice(i + 1, Math.min(i + 9, lines.length)).join(" ");
    const rm = REG_RE.exec(nearby);
    if (rm) {
      friendlyName = rm[1];
    }

    seen.add(guid);
    results.push({ structName, guid, friendlyName, file: file.replace(UE_ROOT + "/", "") });
  }
}

// Sort by friendly name for readability
results.sort((a, b) => (a.friendlyName || a.structName).localeCompare(b.friendlyName || b.structName));

// Output TypeScript
console.log(`// AUTO-GENERATED by src/cli/harvest-guids.ts`);
console.log(`// Harvested from Unreal Engine 5.7.3 source code`);
console.log(`// ${results.length} custom version GUIDs`);
console.log(``);
console.log(`export const CUSTOM_VERSION_GUIDS: Record<string, string> = {`);
for (const r of results) {
  const comment = r.friendlyName ? ` // ${r.structName}` : ` // ${r.structName} (no registration found)`;
  const key = r.guid.toLowerCase();
  const value = r.friendlyName || r.structName;
  console.log(`  "${key}": ${JSON.stringify(value)},${comment}`);
}
console.log(`};`);

process.stderr.write(`Harvested ${results.length} GUIDs\n`);
